#
# starts a osgi console which can be connected to via telnet on port 8999
# all that are useful options during development, but not for a product
osgiRuntimeArguments:
  -console 8999
  -consoleLog
  -clearPersistedState
  -clean

startLevels:
  org.eclipse.core.runtime: 0
  org.eclipse.equinox.common: 2
  org.eclipse.equinox.ds: 2
  org.eclipse.equinox.event: 2
  org.eclipse.equinox.simpleconfigurator: 1
  org.eclipse.osgi: -1

vmProperties:
  org.osgi.framework.bundle.parent: ext

